# -*-python-*-

Import("env")

py_dir = '../vplants/sam4dmaps' if 'vplants' else '../sam4dmaps'

# Build wrappers as shared libraries
# First wrapper
env1 = env.Clone()

sources = env1.ALEAGlob('*.cpp')
target = "_sam4dmaps"
lib = ["sam4dmaps"]

env1.AppendUnique(LIBS=lib)
env1.ALEAWrapper(py_dir, target, sources)


