# This file has been automatically generated by pkg_builder

from openalea.core import *

__name__ = 'sam4Dmaps'
__version__ = '1.0.0'
__license__ = 'CeCILL-C'
__author__ = None
__institutes__ = None
__description__ = ''
__url__ = 'http://openalea.gforge.inria.fr'

__editable__ = 'True'
__icon__ = ''
__alias__ = []

__all__ = []

nuclei_detection = Factory(name='nuclei_detection',
                description='Detect nuclei positions in a SpatialImage',
                category='image',
                nodemodule='vplants.sam4dmaps.nuclei_detection',
                nodeclass='detect_nuclei',
                inputs=[dict(interface=None,name='nuclei_img',value=None), 
                        dict(interface="IInt",name='threshold',value=3000), 
                        dict(interface="IFloat",name='size_range_start',value=0.4), 
                        dict(interface="IFloat",name='size_range_end',value=0.7)],
                outputs=[dict(interface="IDict",name='nuclei_positions')],
                widgetmodule=None,
                widgetclass=None,
               )
__all__.append("nuclei_detection")



fluorescence_ratios = Factory(name='fluorescence_ratios',
                description='Compute fluorescence ratios betwwe two SpatialImage at given points',
                category='image',
                nodemodule='vplants.sam4dmaps.nuclei_detection',
                nodeclass='compute_fluorescence_ratios',
                inputs=[dict(interface=None,name='nuclei_img',value=None), 
                        dict(interface=None,name='signal_img',value=None),
                        dict(interface='IDict',name='nuclei_points',value=None),
                        dict(interface="IFloat",name='nuclei_sigma',value=3.0)],
                outputs=[dict(interface="IDict",name='nuclei_ratios')],
                widgetmodule=None,
                widgetclass=None,
               )
__all__.append("fluorescence_ratios")

point_writer = Factory(name='point_writer',
                description='Save a point dict into a csv file',
                category='image',
                nodemodule='vplants.sam4dmaps.nuclei_detection',
                nodeclass='write_nuclei_points',
                inputs=[dict(interface=None,name='nuclei_positions',value=None), 
                        dict(interface="IFileStr",name='nuclei_filnename',value=None),
                        dict(interface="IStr",name='data_name',value='data'),],
                outputs=[],
                widgetmodule=None,
                widgetclass=None,
               )
__all__.append("point_writer")


point_reader = Factory(name='point_reader',
                description='Read a point dict from a csv file',
                category='image',
                nodemodule='vplants.sam4dmaps.nuclei_detection',
                nodeclass='read_nuclei_points',
                inputs=[dict(interface="IFileStr",name='nuclei_filnename',value=None),],
                outputs=[dict(interface="IDict",name='nuclei_positions',value=None),],
                widgetmodule=None,
                widgetclass=None,
               )
__all__.append("point_reader")

